[build]
  # Build command
  command = "npm run build"

  # Directory to deploy (typically the output of your build script)
  publish = "build"

  # Base directory where files are located
  base = "my-portfolio"

# If your build requires environment variables, you can set them here
# [build.environment]
#   REACT_APP_API_URL = "https://api.example.com"


