[build]
  # Build command
  command = "npm run build"

  # Directory to deploy (typically the output of your build script)
  publish = "build"

# If your build requires environment variables, you can set them here
# [build.environment]
#   REACT_APP_API_URL = "https://api.example.com"

# Redirects for client-side routing (e.g., React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
